name: Release Nightly
on:
  push:
    branches:
      - "integration"
jobs:
  release-nightly:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        java: [ 'openjdk@1.17' ]
    env:
      SBT_OPTS: -Xmx3G -Xss4m
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: modules/webapp
      # - name: Coursier cache
      #   uses: coursier/cache-action@v6
      - name: Set current version
        run:  echo "DOCSPELL_VERSION=$(cat version.sbt | grep version | cut -d= -f2 | xargs)" >> $GITHUB_ENV
      - name: sbt ci ${{ github.ref }}
        run: sbt ci
        env:
          SBT_OPTS: "-Xmx2G -Xss4m"
      - name: sbt make-pkg (${{ env.DOCSPELL_VERSION }})
        run: sbt make-pkg
        env:
          SBT_OPTS: "-Xmx2G -Xss4m"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "integration"
          prerelease: true
          title: "Docspell Integration"
          files: |
            modules/restserver/target/docspell-restserver_${{ env.DOCSPELL_VERSION }}_all.deb
            modules/restserver/target/universal/docspell-restserver-${{ env.DOCSPELL_VERSION }}.zip
            modules/joex/target/docspell-joex_${{ env.DOCSPELL_VERSION }}_all.deb
            modules/joex/target/universal/docspell-joex-${{ env.DOCSPELL_VERSION }}.zip

